admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

administrateur:
    resource: "@AdministrateurBundle/Controller/"
    type:     annotation
    prefix:   /

securite:
  resource: "@SecuriteBundle/Controller/"
  type: annotation
  prefix: /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

filtrerPerception:
  path: /perception/filtrerPerception
  defaults: { _controller: AdministrateurBundle:Perception:filtrerPerception }
  methods: [post]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
