connexion:
    resource: "@ConnexionBundle/Controller/"
    type:     annotation
    prefix:   /

administrateur:
    resource: "@AdministrateurBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

filtrerPerception:
  path: /perception/filtrerPerception
  defaults: { _controller: AdministrateurBundle:Perception:filtrerPerception }
  methods: [post]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
