administrateur:
    resource: "@AdministrateurBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

filtrerPerception:
  path: /perception/filtrerPerception
  defaults: { _controller: AdministrateurBundle:Perception:filtrerPerception }
  methods: [post]
