<?php

namespace AdministrateurBundle\Repository;

/**
 * batimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class batimentRepository extends \Doctrine\ORM\EntityRepository
{
}
