<?php

namespace AdministrateurBundle\Repository;

/**
 * OutilFermetureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutilFermetureRepository extends \Doctrine\ORM\EntityRepository
{
}
