<?php

namespace AdministrateurBundle\Repository;

/**
 * PassPartiel3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassPartiel3Repository extends \Doctrine\ORM\EntityRepository
{
}
