<?php

namespace AdministrateurBundle\Repository;

/**
 * PassPartiel1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassPartiel1Repository extends \Doctrine\ORM\EntityRepository
{
}
