<?php

namespace AdministrateurBundle\Repository;

/**
 * PassPartiel2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassPartiel2Repository extends \Doctrine\ORM\EntityRepository
{
}
