<?php

namespace AdministrateurBundle\Repository;

/**
* PercepteurRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class PercepteurRepository extends \Doctrine\ORM\EntityRepository
{
}
