<?php

namespace AdministrateurBundle\Repository;

/**
 * PerceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
