<?php

namespace AdministrateurBundle\Repository;

/**
* PerceptionRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class PerceptionRepository extends \Doctrine\ORM\EntityRepository
{

  public function recherche(array $options){

    $parameters = array();
    $nom = false;
    $pass1 = false;
    $pass2 = false;
    $qb = $this->createQueryBuilder('p');
    $qb->select('perception')
    ->from('\AdministrateurBundle\Entity\Perception','perception');

    if($options['nom'] != ""){
      $qb->join('perception.percepteur','percepteur')
      ->andWhere('percepteur.nomPercepteur = :nomPercepteur');
      $parameters['nomPercepteur'] = $options['nom'];
      $nom = true;
    }
    if($options['organisation'] != ""){
      if($nom == false){
        $qb->join('perception.percepteur','percepteur');
      }
      $qb->andWhere('percepteur.organisation = :organisation');
      $parameters['organisation'] = $options['organisation'];
    }
    if($options['numeroCle'] != ""){
      $qb->join('perception.variure','variure')
      ->andWhere('variure.nomVariure = :nomVariure');
      $parameters['nomVariure'] = $options['numeroCle'];
    }
    if($options['Pass1'] != "- Select -"){
      $qb->join('perception.passPartiel1','passPartiel1')
      ->andWhere('passPartiel1.nomPass1 = :nomPass1');
      $parameters['nomPass1'] = $options['Pass1'];
      $pass1 = true;
    }
    if($options['Pass2'] != "- Select -" && $pass1 == true){
      $qb->join('perception.passPartiel2','passPartiel2')
      ->andWhere('passPartiel2.nomPass2 = :nomPass2');
      $parameters['nomPass2'] = $options['Pass2'];
      $pass2 = true;
    }
    if($options['Pass3'] != "- Select -" && $pass2 == true){
      $qb->join('perception.passPartiel3','passPartiel3')
      ->andWhere('passPartiel3.nomPass3 = :nomPass3');
      $parameters['nomPass3'] = $options['Pass3'];
    }
    if(empty($parameters)){
      $qb->andWhere('perception.id >= :id');
      $parameters['id'] = 1;
    }
      $qb->setParameters($parameters);
      return $qb->getQuery()->getResult();

  }
}
