<?php

namespace AdministrateurBundle\Repository;

/**
 * ServicePALRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicePALRRepository extends \Doctrine\ORM\EntityRepository
{
}
