<?php

namespace AdministrateurBundle\Repository;

/**
 * service_palrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class service_palrRepository extends \Doctrine\ORM\EntityRepository
{
}
