<?php

namespace AdministrateurBundle\Repository;

/**
 * VariureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariureRepository extends \Doctrine\ORM\EntityRepository
{
}
